### ISSUE TITLE
Integrate with OSS Prow

### ISSUE THREAD

**Issue by krzyzacy** [GoogleCloudPlatform/gke-tracing-demo#7]
(Making a tracking issue since I remember multiple things we need to do here)

TODO:

[x] - make a new service account
[x] - deploy hook & update ingress
[x] - make a new github bot 
[x] - make a new hmac token

The deck is up at https://prow.gflocks.com/, we will make hook listen on https://prow.gflocks.com/hook

cc @chrislovecnm @cjwagner

**Comment by chrislovecnm** [comment]
We already have a bot. Do you want another?

**Comment by cjwagner** [comment]
Whatever bot is used should be dedicated to the Prow instance and not used for anything else. So unless the existing bot is not used for anything we should probably make a new one.

**Comment by krzyzacy** [comment]
made a new service account: `oss-prow@oss-prow.iam.gserviceaccount.com`

Cole how about your drawing? :-)

**Comment by krzyzacy** [comment]
ok made https://github.com/google-oss-robot for now :joy:

**Comment by chrislovecnm** [comment]
No

/woof

**Comment by krzyzacy** [comment]
of course I typo'd on the repo name, sec

**Comment by chrislovecnm** [comment]
😂😂

**Comment by krzyzacy** [comment]
/woof
for the real shiba power!

**Comment by krzyzacy** [comment]
good bot :-)
/this-is-unbearable

**Comment by chrislovecnm** [comment]
🤣🤣🤣

**Comment by krzyzacy** [comment]
(closing for now)
